[tool.poetry]
name = "langchain-rag-lab"
version = "0.1.0"
description = "Un laboratorio de IA conversacional con Gemini y Ollama"
authors = ["Andres Manrique <andress0199@outlook.com>"]
readme = "README.md"
packages = [
    {include = "application", from = "src"},
    {include = "domain", from = "src"},
    {include = "infrastructure", from = "src"},
    {include = "tests"},
    {include = "ragas_evaluation"}
]

[tool.poetry.scripts]
cli = "src.infrastructure.cli.main:app"
ragas = "ragas_evaluation.main:run"

[tool.poetry.dependencies]
python = "~3.11"
langchain = "^1.2.4"
langchain-core = "^1.2.7"
langchain-community = "^0.4.1"
langchain-chroma = "^1.1.0"
langchain-google-genai = "^4.2.0"
langchain-text-splitters = "^1.1.0"
unstructured = "^0.18.27"
python-dotenv = "^1.2.1"
markdown = "^3.10"
ragas = "^0.4.3"
datasets = "^4.5.0"
jupytext = "^1.18.1"
scikit-learn = "^1.8.0"
markitdown = {extras = ["docx", "pdf", "pptx", "xlsx"], version = "^0.1.4"}
sentence-transformers = "^5.2.0"
nltk = "^3.9.2"
yake = "^0.6.0"
langchain-ollama = "^1.0.1"
lancedb = "^0.26.1"
tantivy = "^0.25.1"
pylance = "^1.0.2"
langchain-huggingface = "^1.2.0"
typer = "^0.21.1"
langgraph = "^1.0.7"


[tool.poetry.group.lab.dependencies]
jupyter = "^1.1.1"
ipykernel = "^7.1.0"



[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
pytest-mock = "^3.15.1"
pytest-cov = "^7.0.0"
ruff = "^0.14.11"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"